/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Header from "../components/Header";
import ProductBanner from "../components/ProductBanner";
import { products } from "../lib/products";

export default function Home() {
  return (
    <div className="font-roboto">
      <Head>
        <title>Estamparia Camaleão</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className="w-full min-h-[450px] bg-gray-100 mt-20 flex items-center justify-between px-14">
          <div>
            <h1 className="text-main-purple text-3xl font-bold mb-2">
              Voce tem a ideia, nós cuidamos das cores!
            </h1>
            <p className="text-lg font-medium mb-2">
              Produtos personalizados para você,
              <br />
              sua empresa, seu evento, sua marca e muito mais!
            </p>
            <button className="px-12 py-1 bg-main-purple rounded-md text-white text-lg">
              Faça um orçamento
            </button>
          </div>
          <div className="w-[425px] h-[350px] bg-gray-400 flex items-end"></div>
        </div>
        <div className="my-20 flex gap-2 justify-center items-center">
          <div className="basis-full">
            <img
              src="./assets/camaleao-home.png"
              alt="Logo da empresa Camaleão na frente do local da empresa, com efeito de blur"
            ></img>
          </div>
          <div className="basis-full">
            <h2 className="text-2xl font-bold text-main-purple">Quem somos?</h2>
            <div className="text-sm">
              <p>
                A estamparia Camaleão surgiu em 2022 em Santos/SP com o intuito
                de entregar um produto de extrema qualidade de forma rápida e
                com atendimento personalizado.
              </p>
              <br />
              <p>
                Somos comprometidos com os nossos clientes para suprir qualquer
                demanda e garantindo a satisfação de nossos clientes
              </p>
              <br />
              <p>
                Contamos com uma equipe de profissionais especializados para
                fornecer a melhor experiência possível desde o nosso atendimento
                a entrega de um produto de qualidade
              </p>
              <br />
              <p>
                Nossos produtos abragem aos mais diferentes públicos, tanto para
                o uso pessoal quanto para o profissional
              </p>
              <br />
              <p>Nossos diferenciais:</p>
              <br />
              <ul className="list-disc list-inside">
                <li>Atendimento Personalizado</li>
                <li>Entrega Rápida</li>
                <li>Excelentes Profissionais</li>
                <li>Equipamento de Ponta</li>
              </ul>
            </div>
          </div>
        </div>
        <div className="flex flex-col justify-center items-center mb-20">
          <h2 className="text-[40px] text-main-purple font-bold mb-10">
            Como comprar?
          </h2>
          <div className="flex justify-center items-center gap-5">
            <div className="w-[145px] h-[145px] bg-gray-400"></div>
            <i className="bi bi-arrow-right text-5xl"></i>
            <div className="w-[145px] h-[145px] bg-gray-400"></div>
            <i className="bi bi-arrow-right text-5xl"></i>
            <div className="w-[145px] h-[145px] bg-gray-400"></div>
            <i className="bi bi-arrow-right text-5xl"></i>
            <div className="w-[145px] h-[145px] bg-gray-400"></div>
            <i className="bi bi-arrow-right text-5xl"></i>
            <div className="w-[145px] h-[145px] bg-gray-400"></div>
          </div>
        </div>
        <div className="flex flex-col justify-center items-center px-20">
          <h2 className="text-main-purple font-bold text-[40px] mb-10">
            Perguntas Frequêntes
          </h2>
          <div className="flex gap-14 max-w-5xl">
            <ul className="flex flex-col gap-10 text-sm text-center">
              <li>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation
              </li>
            </ul>
            <ul className="flex flex-col gap-10 text-sm text-center">
              <li>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation
              </li>
            </ul>
          </div>
        </div>
        <div className="flex gap-14 justify-center items-center my-20">
          <div className="w-[372px] h-[372px] bg-gray-400 text-[40px] text-white flex justify-center items-center">
            sem pedido mínimo
          </div>
          <div className="w-[372px] h-[372px] bg-gray-400 text-[40px] text-white flex justify-center items-center">
            Impressão DTG
          </div>
        </div>
        <div>
          <h2 className="text-main-purple font-bold text-[40px] mb-10 text-center">
            Faça um orçamento
          </h2>
          <div className="w-full h-[450px] bg-gray-400"></div>
        </div>
        <div>
          {products.map((item, key) => (
            <ProductBanner props={item} key={key} />
          ))}
        </div>
      </main>

      <Footer />
    </div>
  );
}
