/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Header from "../components/Header";
import ProductBanner from "../components/ProductBanner";
import { productsBanner } from "../lib/productsBanner";

export default function Home() {
  return (
    <div className="font-roboto">
      <Head>
        <title>Estamparia Camaleão</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className="w-full min-h-[650px] bg-gray-100 flex justify-center">
          <div className="flex items-center justify-between px-14 w-full max-w-[1400px]">
            <div>
              <h1 className="text-main-purple text-3xl font-bold mb-2">
                Voce tem a ideia, nós cuidamos das cores!
              </h1>
              <p className="text-lg font-medium mb-2">
                Produtos personalizados para você,
                <br />
                sua empresa, seu evento, sua marca e muito mais!
              </p>
              <button className="px-12 py-1 bg-main-purple rounded-md text-white text-lg">
                Faça um orçamento
              </button>
            </div>
            <div className="w-[425px] h-[350px] bg-gray-400 flex items-end"></div>
          </div>
        </div>
        <div className="my-20 flex gap-2 justify-center items-center max-w-[1400px] mx-auto">
          <div className="basis-full">
            <img
              src="./assets/camaleao-home.png"
              alt="Logo da empresa Camaleão na frente do local da empresa, com efeito de blur"
            ></img>
          </div>
          <div className="basis-full">
            <h2 className="text-2xl font-bold text-main-purple">Quem somos?</h2>
            <div className="text-sm">
              <p>
                A estamparia Camaleão surgiu em 2022 em Santos/SP com o intuito
                de entregar um produto de extrema qualidade de forma rápida e
                com atendimento personalizado.
              </p>
              <br />
              <p>
                Somos comprometidos com os nossos clientes para suprir qualquer
                demanda e garantindo a satisfação de nossos clientes
              </p>
              <br />
              <p>
                Contamos com uma equipe de profissionais especializados para
                fornecer a melhor experiência possível desde o nosso atendimento
                a entrega de um produto de qualidade
              </p>
              <br />
              <p>
                Nossos produtos abragem aos mais diferentes públicos, tanto para
                o uso pessoal quanto para o profissional
              </p>
              <br />
              <p>Nossos diferenciais:</p>
              <br />
              <ul className="list-disc list-inside">
                <li>Atendimento Personalizado</li>
                <li>Entrega Rápida</li>
                <li>Excelentes Profissionais</li>
                <li>Equipamento de Ponta</li>
              </ul>
            </div>
          </div>
        </div>
        <div className="flex flex-col justify-center items-center mb-20">
          <h2 className="text-[40px] text-main-purple font-bold mb-10">
            Como comprar?
          </h2>
          <div className="flex justify-center items-center gap-5">
            <div className="relative">
              <div className="w-[145px] h-[145px] bg-main-lime-green rounded-2xl shadow-lg shadow-zinc-400  flex justify-center items-center">
                <img
                  src="./assets/shirt-icon.svg"
                  alt="Icone de camiseta"
                ></img>
              </div>
              <p className="text-center text-main-lime-green font-bold absolute bottom-[-60px] left-0 right-0 mx-auto">
                Escolha o modelo
                <br /> e a cor da camiseta
              </p>
            </div>

            <i className="bi bi-arrow-right text-4xl"></i>

            <div className="relative">
              <div className="w-[145px] h-[145px] bg-main-lime-green rounded-2xl shadow-lg shadow-zinc-400  flex justify-center items-center">
                <img
                  src="./assets/art-icon.svg"
                  alt="Icone de paleta de tinta"
                ></img>
              </div>
              <p className="text-center text-main-lime-green font-bold absolute bottom-[-60px] left-0 right-0 mx-auto">
                Envie a imagem
                <br /> a ser estampada
              </p>
            </div>

            <i className="bi bi-arrow-right text-4xl"></i>

            <div className="relative">
              <div className="w-[145px] h-[145px] bg-main-lime-green rounded-2xl shadow-lg shadow-zinc-400  flex justify-center items-center">
                <img
                  src="./assets/resize-icon.svg"
                  alt="Icone de aumentar/diminuir imagem"
                ></img>
              </div>
              <p className="text-center text-main-lime-green font-bold absolute bottom-[-80px] left-0 right-0 mx-auto">
                Escolha
                <br /> o posicionamento
                <br /> da imagem
              </p>
            </div>

            <i className="bi bi-arrow-right text-4xl"></i>

            <div className="relative">
              <div className="w-[145px] h-[145px] bg-main-lime-green rounded-2xl shadow-lg shadow-zinc-400  flex justify-center items-center">
                <img src="./assets/coins-icon.svg" alt="Icone de moedas"></img>
              </div>
              <p className="text-center text-main-lime-green font-bold absolute bottom-[-60px] left-0 right-0 mx-auto">
                Defina a
                <br /> quantidade
              </p>
            </div>

            <i className="bi bi-arrow-right text-4xl"></i>

            <div className="relative">
              <div className="w-[145px] h-[145px] bg-main-lime-green rounded-2xl shadow-lg shadow-zinc-400 flex justify-center items-center">
                <img
                  src="./assets/happy-icon.svg"
                  alt="Icone de pessoa feliz"
                ></img>
              </div>
              <p className="text-center text-main-lime-green font-bold absolute bottom-[-60px] left-0 right-0 mx-auto">
                Agora é só
                <br /> aproveitar!
              </p>
            </div>
          </div>
        </div>
        <div className="flex flex-col justify-center items-center px-20 pt-20">
          <h2 className="text-main-purple font-bold text-[40px] mb-10">
            Perguntas Frequêntes
          </h2>
          <div className="flex gap-14 max-w-5xl">
            <ul className="flex flex-col gap-10 text-sm text-center">
              <li>
                <h4>Existe alguma quantidade minima?</h4>
                <p>Não! O pedido mínimo para produção é de uma unidade</p>
              </li>
              <li>
                <h4>Posso levar minha camisetas para estampar?</h4>
                <p>
                  Sim, sua camiseta sendo feita de algodão nós conseguimos
                  estampar.
                </p>
              </li>
              <li>
                <h4>Posso estampar qualquer imagem na camiseta?</h4>
                <p>
                  Sim, é possível estampar qualquer imagem desde que tendo
                  qualidade e tamanho para impressão.
                </p>
              </li>
            </ul>
            <ul className="flex flex-col gap-10 text-sm text-center">
              <li>
                <h4>
                  Posso comprar camisetas de cores diferentes para minha
                  empresa?
                </h4>
                <p>
                  Sim! Você pode escolher cores diferentes de nosso catálogo e
                  variar entre elas em seu pedido.
                </p>
              </li>
              <li>
                <h4>Vocês enviam para todo Brasil?</h4>
                <p>Sim! Podemos enviar seu pedido para todo Brasil.</p>
              </li>
              <li>
                <h4>
                  Tenho uma ideia de estampa mas não consigo desenhar, vocês
                  conseguem me ajudar?
                </h4>
                <p>
                  Sim! Temos uma equipe de ilustradores aptos a ajudar a tirar
                  sua ideia do papel e virar uma camiseta incrível.
                </p>
              </li>
            </ul>
          </div>
        </div>
        <div className="flex gap-14 justify-center items-center my-20">
          <div className="w-[372px] h-[372px] bg-[url(/assets/resting-men.png)] inside-container-text-shadow text-center font-extrabold shadow-lg shadow-zinc-400 text-[40px] text-white flex justify-center items-center">
            SEM PEDIDO MÍNIMO
          </div>
          <div className="w-[372px] h-[372px] bg-[url(/assets/printer.png)] text-[40px] inside-container-text-shadow font-extrabold shadow-lg shadow-zinc-400 text-white flex justify-center items-center">
            IMPRESSÃO DTG
          </div>
        </div>
        <div>
          <h2 className="text-main-purple font-bold text-[40px] mb-10 text-center">
            Faça um orçamento
          </h2>
          <div className="w-full h-[450px] bg-gray-400"></div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
